encryptionsalt: v1:YTkee7kQQTg=:v1:/DTnG8Yzsf51l4Y1:TKBCfVPu4nIb6hRre/lmljkd6MvV3w==
config:
  azure-ts-aks-helm:password:
    secure: v1:3pzgBBnBWlOv4fLo:SiGeooLpA7bGsTuvzzesVnZR0Zpm8EGDSl0fACxLEg==
  azure-ts-aks-helm:sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxdJbW9gbZlQ1AHimWOEHiv1O/StpiSbrBxhu/RVM50jQeICWUhpLEHFOnnk9XYkbJS0ksJ9zzVObZxrNPSA0sq1ag8xsSD2pDWbsLHGjOeRIPOTBCArI6gggIzmiHWr2bY3l3gBm0R9Z/ibPzORpbbj11IRwBSbZJ3Up090zd2YnNEZyd/fxdX9awQ27MAcC7MgX8bbFFHkxcamGxlQSbxeF5xy8ZfrQVMlVjRtBzYm42KCqTn3FXdKgJYntwqrvOwP96+oXVRKQtofX7dtu7zgUo4/wbPBg6Qua1xz1p0ogY+TTVNAh8mnHI30DpPk/r2NInp01PuKfgSRdIy2jF
    my-comment
  azure:clientId: b7e2dd6c-e659-4822-846c-b27490bc72a4
  azure:clientSecret:
    secure: v1:XUXvtIe5Flicb9T9:zVqxFDtN5pB0nIrfpglwOv57V+Fjl4ZnEyoDOnZ5/LAv2OwyZx4IKWIW/qXBr8g2
  azure:environment: public
  azure:subscriptionId: 02a60b58-610b-4e92-9714-fe8cc4c2911b
  azure:tenantId: dbd6664d-4eb9-46eb-99d8-5c43ba153c61
